### ISSUE TITLE
React Native Call not receiving in Background

### ISSUE THREAD

**Issue by danishkhalid1** [cometchat-pro/react-native-chat-app#12]
Hi,
I am integrating CometChat library in React native application. The call feature is working fine when app is in open state, but when the app is in background state the call is not receiving. Please guide me how can I integrate Background Call Feature
Thanks in advance

- Version used:
React Native Version 0.61.3
CometChat Version 2.1.4
CometChat Call Version 1.0.3

**Comment by mubashirngi** [comment]
There are lots of issues I have faced while integrating this library I have  changed my App version to work with this library there should be a proper support 
The same issue after integrating this library background call feature is not available
also on the Ios when turning the video call to audio it shows a blank screen

**Comment by mayur-bhandari** [comment]
Hello @danishkhalid1 ,

You can integrate push notification using our Push Notification extension and then get the notification for calls when the app is in the background or killed state and then show appropriate calling UI on the click of the notification.

**Comment by mayur-bhandari** [comment]
> Ios when turning the video call to audio it shows a blank screen

Hello @mubashirngi,

We are looking into this issue and we will get back to you as soon as we have any update.

**Comment by TirathBhuva** [comment]
> Ios when turning the video call to audio it shows a blank screen

Hello @mubashirngi,

This issue has been resolved in our latest SDK. Kindly update @cometchat-pro/react-native-calls and @cometchat-pro/react-native-chat to the latest version.

**Comment by proveshapyne** [comment]
Hello,

I am closing this ticket due to inactivity. If you need further technical help, please reach out to us at help@cometchat.com.

Regards,
Provesha

**Comment by pankajvaghelav2** [comment]
Hey, We are trying out the Kitchen Sink app, it's using latest versions. Still having same error, i.e. no call when app is in background.
