### ISSUE TITLE
Single Mode android to Ios giving blank screen while video off 

### ISSUE THREAD

**Issue by mubashirngi** [cometchat-pro/react-native-chat-app#13]
### Describe the problem
While calling from android to Ios or Ios to android when I turned the video Off a blank screen display and we don't have the option to turn the video on again 
I tried with the custom layout with custom buttons, then after I turned the video off blank screen display but custom icons showed this time but the video is not turning on again 
### What was the expected behavior?
The video turnOn turnOff should work fine on single-mode on both android and Ios
> Tell us about the behavior you expected to see

### Reproduction

- Step 1. Test the Application on android and ios Devices initiate call from android to Ios or Ios to android
- Step 2. Turn the video off. (blank screen display) on default Layout 
- Step 3. With custom, buttons turn off the video blank screen display with your custom icons try to turn on the video again
nothing will happen 
- ...

### Environment
Android ,IOS

React native Version "0.61.3"
 "@cometchat-pro/react-native-calls": "^1.0.3",
 "@cometchat-pro/react-native-chat": "^2.1.4",

**Comment by mayur-bhandari** [comment]
Hello @mubashirngi,

We are looking into this issue and we will get back to you as soon as we have any update.

**Comment by mayur-bhandari** [comment]
Hello @mubashirngi 

We have released an update to our Calling Component. Please update the React Native SDK (@cometchat-pro/react-native-chat) to 2.1.7 & React Native Calling Component (@cometchat-pro/react-native-calls) to 1.0.7. Please let us know if you still face this issue.

**Comment by mubashirngi** [comment]
Hi @mayur

Yes I have reviewed and implemented it much better than the previous one
still there are some issues I will let you know later
I also request you to update the documentation and make it simple and
explain things by steps It will save time of developers
like the background calling feature you told me that we can do it by
notification I did it but I didn't find that in the docs
things can be great and I would like to use and recommend to others if you
work on the things which I told
Thanks

**Comment by proveshapyne** [comment]
Hello @mubashirngi,

Glad you were able to implement this. 
Thank you for the feedback! We would love to hear about your experience with CometChat. Please feel free to reach out to us at help@cometchat.com to continue this conversation.

Looking forward to hearing from you!

Regards,
Provesha
