### ISSUE TITLE
In push notification not receiving notification payload

### ISSUE THREAD

**Issue by vishalrakholiya** [cometchat-pro/react-native-chat-app#17]
While App is in the background or open state in messaging().onMessage event only receives data payload and notification payload not receive.

So, notification not working, while from API  push notification is working.

Here are details of package.json:

"react-native": "0.63.4",
"@react-native-firebase/app": "^10.8.0",
"@react-native-firebase/messaging": "^10.8.0",
"@cometchat-pro/react-native-calls": "^1.0.8",
"@cometchat-pro/react-native-chat": "^2.2.1",

**Comment by prathamesh-majgaonkar** [comment]
At the moment, we do not send the `notification` key in the payload for React Native. However, we include the data payload making it a Data notification. It gives you more control while displaying notifications.

If the `notification` key is present in the payload, the notifications directly land up in the Notification tray. As a developer, you do not get to display those programmatically.

Having said that, we are also working on providing Push Notification extension settings where you can toggle the `notification` key in the payload.

You can track this feature request using the following link: https://feedback.cometchat.com/cometchat-pro-feature-requests/p/push-notification-notification-key

**Comment by vishalrakholiya** [comment]
Then, what about the kill state of application I don't receive a notification.

**Comment by prathamesh-majgaonkar** [comment]
I have checked and I can confirm that I am able to receive notifications on Android even when the app is killed.

**Comment by prathamesh-majgaonkar** [comment]
Have you checked our React Native Push Notifications Sample app?
https://github.com/cometchat-pro/react-native-chat-push-notification-app

**Comment by vaibhav22c** [comment]
I'm also facing this type of issue 
while application foreground or background I manage it but 
notification does not receive after application kill/close

**Comment by prathamesh-majgaonkar** [comment]
Is it on Android, iOS or both?
Have you tried using this React Native Sample app for push notifications?
https://github.com/cometchat-pro/react-native-chat-push-notification-app

**Comment by vaibhav22c** [comment]
it's working only on android
if app is kill/close on IOS then notification does not display in your app

**Comment by prathamesh-majgaonkar** [comment]
By default, we are sending Data Notifications for React Native. So, you as a developer gets full control over displaying the notification.
If you want the OS to handle it, you can choose to include the notification key in the payload from the Push Notification extension settings for React Native.

![image](https://user-images.githubusercontent.com/66062414/118924934-73bf2000-b95b-11eb-9770-837b438fe042.png)
