### ISSUE TITLE
reactions of messages are not working 

### ISSUE THREAD

**Issue by azzi907** [cometchat-pro/react-native-chat-app#22]
### Describe the problem

> in chat messages reaction pop up opens up and if you choose a reaction nothing happens.

### What was the expected behaviour?

> selected  reaction should be shown with the message. 

### Reproduction

> With each message there is a small reaction icon when we touch on it a pop up opens from where you can select a reaction and if you choose any reaction nothing happens 

> **Note**: If clear, reproducible steps or the smallest sample app demonstrating misbehaviour cannot be provided, we may not be able to follow up on this bug report.

- Step 1..
- Step 2..
- ...

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behaviour
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

-branch :master
- **Version used:**
- **Other modules/plugins/libraries that might be involved:**

**Comment by mayur-bhandari** [comment]
Hello @azzi907,

Can you please confirm that you have enabled the Reactions extension for your app on the [CometChat Dashboard](https://app.cometchat.com/)? Also, can you please share the error logs when you try to add a reaction (if any)?

**Comment by azzi907** [comment]
@mayur-bhandari i will verify ,
