### ISSUE TITLE
there is no method to delete a conversation.

### ISSUE THREAD

**Issue by azzi907** [cometchat-pro/react-native-chat-app#23]
### Describe the problem

> In inbox there is no method to delete a conversation.

### What was the expected behaviour?

> There should be some way of deleting a conversation.

### Reproduction

> In the inbox where you can choose to continue a group chat or chat with a person there is no way of deleting a conversation.

### Environment

-branch: main

**Comment by mayur-bhandari** [comment]
Hello @azzi907,

A conversation can be deleted using our Delete Conversation REST API. You can read more about the Delete Conversation API [here](https://prodocs.cometchat.com/reference#delete-conversation). Also, we have created a feature request for the same. You can vote for the feature request [here](https://feedback.cometchat.com/cometchat-pro-feature-requests/p/ability-to-delete-a-chat-from-recent-conversations).

**Comment by azzi907** [comment]
![Screenshot 2021-04-21 at 2 44 52 PM](https://user-images.githubusercontent.com/10634923/115533495-3316ad00-a2b0-11eb-87f7-92f981210ffc.png)
i am getting this error with the api key. does my API keys has no delete conversation privileges

**Comment by azzi907** [comment]
![Screenshot 2021-04-21 at 3 10 50 PM](https://user-images.githubusercontent.com/10634923/115536994-cc938e00-a2b3-11eb-859e-f2b477e4e2dd.png)
on behalf of UID  not acceptable . please see the screenshot above also on the api docs there is note: "The deleted conversation and the messages will not be available for the user specified in the URL (onBehalfOFUID)".
i am unable to understand what does it means. Can you please elaborate this.

**Comment by azzi907** [comment]
@mayur-bhandari can you see error in screenshot above i am sending params as well, am I doing anything wrong here ?

**Comment by mayur-bhandari** [comment]
Hello @azzi907,

The parameter `onBehalfOfUid` is a path parameter but you are sending it as a query parameter. Please replace `onBehalfOfUid` in the URL with the UID on whose behalf you want to delete the conversation. In your case, the URL should be as follows `https://api-us.cometchat.io/v2.0/users/{{UID}}/conversations?conversationId={{conversationId}}.

Replace {{UID}} with the UID & {{conversationId}} with the conversationId you want to delete.

Hope this helps.

**Comment by azzi907** [comment]
@mayur-bhandari i have implemented this,
Should i send pull request so you guys can review and merge? 

<img width="372" alt="Screenshot 2021-05-03 at 6 35 48 PM" src="https://user-images.githubusercontent.com/10634923/116882896-66f1bb00-ac3e-11eb-8cfe-5b10e90b9f3f.png">
