### ISSUE TITLE
Take photo does not works and quits back to compose message screen

### ISSUE THREAD

**Issue by azzi907** [cometchat-pro/react-native-chat-app#24]
### Describe the problem

> Take photo does not works and quits back to compose message screen

### What was the expected behavior?

> it show open and after taking a photo it should send that image to the user being chatted with.

### Reproduction

> open conversation with a user or in a group and select take photo option from the options from bottom sheet. 

> - When you choose a conversation with a user or a group. 
> - Inside the chat screen. beside message composer input.
> - When you choose the take photo option from the bottom sheet that opens when you press plus button.

**Comment by TirathBhuva** [comment]
Hey azzi907,
	Looks like your app does not have camera permission, can you check whether you have given camera permission?

**Comment by azzi907** [comment]
@TirathBhuva  camera permission are given already i checked already

**Comment by azzi907** [comment]
@TirathBhuva  any update on this?

**Comment by TirathBhuva** [comment]
Hey @azzi907 ,
 We were able to reproduce this issue on our end we will fix this in the next release. 
For now, you can use this patch.
In the ComposerActions.js replace the takePhoto function with the below function. This should solve the issue.

```
takePhoto = async () => {
    try {
      let granted = null;
      if (Platform.OS === 'android') {
        granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.CAMERA,
          {
            title: 'CometChat Camera Permission',
            message: 'CometChat needs access to your camera ',
            buttonNegative: 'Cancel',
            buttonPositive: 'OK',
          },
        );
      }

      if (
        Platform.OS === 'ios' ||
        granted === PermissionsAndroid.RESULTS.GRANTED
      ) {
        launchCamera(
          {
            includeBase64: false,
          },
          (response) => {
            this.sheetRef.current.snapTo(1);
            this.props.close();
            if (response.didCancel) {
              return null;
            }
            let type = null;
            let name = null;
            if (Platform.OS === 'ios' && response.fileName !== undefined) {
              name = response.fileName;
            } else {
              type = response.type;
              name = 'Camera_001.jpeg';
            }
            const file = {
              name: Platform.OS === 'android' ? response.fileName : name,
              type: response.type,
              uri:
                Platform.OS === 'android'
                  ? response.uri
                  : response.uri.replace('file://', ''),
            };
            this.props.sendMediaMessage(file, CometChat.MESSAGE_TYPE.IMAGE);
          },
        );
      }
    } catch (err) {
      this.sheetRef.current.snapTo(1);
      this.props.close();
    }
  };
```

**Comment by azzi907** [comment]
@TirathBhuva thanks
