### ISSUE TITLE
There is no way to add a group picture and edit group name

### ISSUE THREAD

**Issue by azzi907** [cometchat-pro/react-native-chat-app#25]
### Describe the problem

> There is no way to add a group picture. and there is no way to edit group name.

### What was the expected behavior?

> there should an option to add group picture while creating a group. and edit the group properties. there should also be some way  of editing group name.

**Comment by paarthsabharwal** [comment]
Hi @azzi907 , we can help with this.

For creating groups please refer to our documentation: https://prodocs.cometchat.com/docs/react-native-groups-create-group 
Please change the parameters as per the relevant groups.

For editing/updating group details please refer to:
https://prodocs.cometchat.com/docs/react-native-groups-update-group.

Feel free to get back to me if you have any questions.

**Comment by azzi907** [comment]
@paarthsabharwal  thanks but I have a question, It accepts the image URL.  
is there any way we can upload the group icon to cometchat server first ?

**Comment by azzi907** [comment]
new Group(String GUID, String name, String groupType, String password, String icon, String description)

**Comment by proveshapyne** [comment]
Hi @azzi907,

I am closing this ticket. We can continue our conversation through email.
Thank you.

Regards,
Provesha
