### ISSUE TITLE
Camera Autofocus feature should not be required by pro-android-calls-sdk-2.0.0 dependency

### ISSUE THREAD

**Issue by azzi907** [cometchat-pro/react-native-chat-app#27]
### Camera Autofocus feature should not be required by pro-android-calls-sdk-2.0.0 dependency. because of this app is not compatible on devices which autofocus feature. 

> Provide a clear and concise description of the issue

### What was the expected behavior?

>  Camera Autofocus feature should not be required by pro-android-calls-sdk-2.0.0 dependency. because of this app is not compatible on devices which lack autofocus feature. you should add the following to  mentioned manifest file of pro-android-calls-sdk-2.0.0 depandency.
 should be added:  android:required="false"

here

![cometchat send](https://user-images.githubusercontent.com/10634923/117616412-892a9200-b184-11eb-8b49-b2b2fa8ed143.png)

**Comment by azzi907** [comment]
@mayur-bhandari any idea?

**Comment by TirathBhuva** [comment]
Hey @azzi907,
	We have removed the Camera Autofocus feature in our latest calling component, you can upgrade the  @cometchat-pro/react-native-calls to the latest version and it will solve the problem.

**Comment by azzi907** [comment]
@TirathBhuva 

Amazon said you need to make one more change, as well 

Change this line in your manifest:
    <uses-feature android:name="android.hardware.camera" />

to this:
    <uses-feature android:name="android.hardware.camera" android:required="false"/>
