### ISSUE TITLE
React native ios project don't work with the new version of React Native Call

### ISSUE THREAD

**Issue by zainebzaineb** [cometchat-pro/react-native-chat-app#28]
I have a huge problem and wishing that you could help me with it. Actually ,i am working in react native project iOS version and i'm trying to run the project in « CometChatWorkspace/cometchat-app » with the new version of React Native Calls « @cometchat-pro/react-native-calls@2.0.2 » and  React Native chats « @cometchat-pro/react-native-chat@2.3.1 ». So when I run pod install I have this issue

![ios issue](https://user-images.githubusercontent.com/36507391/118795653-b79a2280-b892-11eb-8d00-d5ed10949217.png)

I would be very grateful if you could compile it with the new version and i really appreciate it if you could deal with this matter urgently. 

Thanks in advance.

**Comment by mayur-bhandari** [comment]
Hello @zainebzaineb,

Please update the ios version mentioned in Podfile to 11.0.
In your Podfile search for this line,

`platform :ios, 'xx.x'` & replace it with `platform :ios, '11.0'`

Then from the CometChatWorkspace/cometchat-app/ios folder run the following commands,

> pod deintegrate
> pod install

Hope this helps.

**Comment by zainebzaineb** [comment]
Hello @mayur-bhandari,

I update the ios version in Podfile to '11.0' then i'm runing the pod deintegrate commande and pod install, but i have the same issue

**Comment by jitvarpatil** [comment]
Hello @zainebzaineb 

Did you try running `pod install --repo-update` command?

**Comment by zainebzaineb** [comment]
Hello @jitvarpatil 

yes i did it but the same error.

**Comment by jitvarpatil** [comment]
@zainebzaineb This is happening as your local pod repo is not updated.
Can you try
`pod install --repo-update` 
`pod repo update`
`pod update`

multiple times and then run
`pod deintegrate`
`pod install`

**Comment by proveshapyne** [comment]
Hi @zainebzaineb,

Thank you for confirming this.

If you need further technical assistance, you can reach out to us through your CometChat dashboard or email us at help@cometchat.com.

Regards,
Provesha
