### ISSUE TITLE
CometChatCalls

### ISSUE THREAD

**Issue by etherealSunshine** [cometchat-pro/react-native-chat-app#43]
### Describe the problem
Unable to install CometChatCalls when running arch -x86_64 pod install.

[!] Error installing CometChatCalls
[!] /opt/anaconda3/bin/curl -f -L -o /var/folders/zr/0w5gcg69431fwbkc15gfdmvm0000gn/T/d20211012-3769-1db3yfz/file.zip https://library.cometchat.io/ios/v2.0/xcode12/CometChatCalls_2_0_3.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 27  332M   27 91.9M    0     0  1219k      0  0:04:39  0:01:17  0:03:22 2430k
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 54

**Comment by proveshapyne** [comment]
Hey @etherealSunshine,

I hope Jitvar's suggestions helped resolve the issue you were facing. Please feel free to reach out to us at help@cometchat.com for any further technical help.

Regards,
Provesha
