### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by danikenan** [cometchat-pro/react-native-chat-app#47]
### Describe the problem

> pod install fails

the lock file is incorrect and contains refs to `CometChatCalls (= 2.0.3)` instead of `CometChatCalls (= 2.1.1)`
like the `cometchat-app/ios/Pods/Local Podspecs/react-native-cometchat-rtc.podspec.json` json file requires.

```
  "dependencies": {
    "React": [

    ],
    "CometChatCalls": [
      "2.1.1"
    ]
  }
 ```

### What was the expected behavior?

> pod install should succeed 

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

follow the steps in the readme, using v3 branch (or master).

```
➜  ios pod install
Auto-linking React Native modules for target `example`: RNCAsyncStorage, RNCMaskedView, RNCPicker, RNFastImage, RNGestureHandler, RNReanimated, RNScreens, RNSound, RNVectorIcons, react-native-cometchat-rtc, react-native-document-picker, react-native-image-picker, react-native-keep-awake, react-native-safe-area-context, react-native-video, react-native-webview, and rn-fetch-blob
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "CometChatCalls":
  In snapshot (Podfile.lock):
    CometChatCalls (= 2.0.3, = 2.1.0)

  In Podfile:
    react-native-cometchat-rtc (from `../node_modules/@cometchat-pro/react-native-calls`) was resolved to 2.1.1, which depends on
      CometChatCalls (= 2.1.1)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `CometChatCalls` inside your development pod `react-native-cometchat-rtc`.
   You should run `pod update CometChatCalls` to apply changes you've made.
   
   ```
   
![image](https://user-images.githubusercontent.com/887919/141465987-67e8d032-4de6-4bba-a3e1-9a9f9b5060f1.png)

> - Screenshots

### Environment

> Please provide the following:

- **Version used:**
- **Other modules/plugins/libraries that might be involved:**

**Comment by jitvarpatil** [comment]
Hi @danikenan Please try `pod repo update` & `pod install --repo-update` & `pod update CometChatCalls` and try `pod install` again.
