### ISSUE TITLE
Notification not receiving for a group call

### ISSUE THREAD

**Issue by gajjartejas** [cometchat-pro/react-native-chat-app#52]
### Describe the problem

the notification for call received only for one to one/direct call but not working for the group call. Once call init, server should send notification to each member.

### What was the expected behaviour?

server should send notification to each member.

### Reproduction

Enable chat widget and enabled all notification related to the call.

### Environment

`node v12.14.0`
`react-native": "0.64.2`

- **Version used:**
Right now I am using below version for SDK
```
"@cometchat-pro/react-native-calls": "^2.1.1-beta3",
"@cometchat-pro/react-native-chat": "^3.0.0",
```

**Comment by TirathBhuva** [comment]
Hey @gajjartejas,
      In our sample app and UI kit, we are using Direct calling for video calls. You can learn more about direct calls [here](https://www.cometchat.com/docs/react-native-chat-sdk/calling-direct-calling).  We just send a [custom message](https://www.cometchat.com/docs/react-native-chat-sdk/messaging-send-message#custom-message) that has the call information. If you want a notification for that then you need to add metaData to the custom message. you can find more detailed explanations over [here](https://www.cometchat.com/docs/extensions/react-native-push-notifications#handle-custom-messages).

**Comment by gajjartejas** [comment]
Hi @TirathBhuva Is it possible to set custom notification sound key and `android_channel_id` to custom message?

![Screenshot 2022-01-21 at 7 03 53 PM](https://user-images.githubusercontent.com/14052969/150535857-7d36b435-b3ab-4d07-b0b8-f9c729970332.png)

**Comment by prathamesh-majgaonkar** [comment]
Hey @gajjartejas, currently we don't have the features to allow custom sound and channel IDs.
I am sharing the feature requests for the same:
1. https://feedback.cometchat.com/extensions/p/push-notifications-custom-sound
2. https://feedback.cometchat.com/extensions/p/push-notifications-support-for-channels
