### ISSUE TITLE
Cannot install using yarn

### ISSUE THREAD

**Issue by morph3ux** [cometchat-pro/react-native-chat-app#8]
I tried to install the example app using yarn and it crashes. Only npm install seems to work atm.

**Comment by mayur-bhandari** [comment]
Hello @morph3ux ,

Can you please try installing the latest SDK v2.1.0 using yarn? Please let us know if you still face the same issue.

**Comment by paarthsabharwal** [comment]
Hi @morph3ux ,
Hope you had a chance to update to v2.1.0, which should resolve the issue.

**Comment by morph3ux** [comment]
Yes, I did. Thanks!
