### ISSUE TITLE
Getting error while accepting a call

### ISSUE THREAD

**Issue by Mike-Van** [cometchat-pro/react-native-chat-app#9]
Hi so i'm trying out the latest version of react native sdk. specifically for calling. And now im getting this error when accpepting a call. 
```
Invariant violation: requireNativeComponent: "CometChatRTCView" was not found in the UI Manager.
```
it appears to becoming from `node_modules/@cometchat-pro/react-native-calls/Callscreen.js`

**Comment by mayur-bhandari** [comment]
Hello @Mike-Van ,

It looks like you haven't added the dependency in your gradle file. Please go through the documentation for adding the dependency in your gradle file.  

Documentation: https://prodocs.cometchat.com/v2.1/docs/react-native-setup#add-the-cometchat-dependency

**Comment by Mike-Van** [comment]
hi so i followed the dependencies adding procedure in the docs. and now i can acceept the call but. on android, the call screen is kinda froze and on ios, the ios is blacked and in xcode it threw the error like below
<img width="1440" alt="Screen Shot 2020-07-29 at 3 12 58 PM" src="https://user-images.githubusercontent.com/29220303/88775085-7a9f5b00-d1ae-11ea-853e-9e3e6464171b.png">

**Comment by mayur-bhandari** [comment]
Hello @Mike-Van 

On Android, please make sure you have provided camera and microphone access. 

On iOS, you need to add camera and microphone access in your Info.plist file. Please add the necessary permissions in the Info.plist file and check once again.

**Comment by Mike-Van** [comment]
ok thanks. i thought the sample app already had all that configs setup. but now after enabling access. i can do the call now. appreciate the assistance :D
