### ISSUE TITLE
Can't run locally on iOS

### ISSUE THREAD

**Issue by alemar11** [cometchat-pro/react-native-chat-app#90]
### Describe the problem

Can't run the sample locally on an iOS simulator using `npx react-native run-ios --simulator="iPhone 15"`

```
The following build commands failed:
	CompileC  ... CometChatWorkspace/ios/Pods/FlipperKit/iOS/FlipperKit/FlipperPlatformWebSocket.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'FlipperKit' from project 'Pods')

```

**Comment by alemar11** [comment]
```
git clone https://github.com/cometchat-pro/react-native-chat-app.git -b v4

cd CometChatWorkspace

npm install --legacy-peer-deps

cd ios && pod update

npm start

npm run ios -- --udid=“IPHONE SIMULATORE ID HERE"
```

**Comment by alemar11** [comment]
Hi,
the problem remains the same I guess

<img width="774" alt="Screenshot 2024-03-13 alle 18 31 57" src="https://github.com/cometchat/cometchat-sample-app-react-native/assets/1273940/8d122010-6244-4293-8954-0d77452a9da7">

I'm using Xcode 15.3 with Sonoma 14.4
The issues seems the same [described here](https://github.com/facebook/react-native/issues/43335)

**Comment by mayur-bhandari** [comment]
Hi,

This is an issue in the Flipper SDK in Xcode 15. There is a [fix](https://github.com/facebook/flipper/commit/b3dcdb87f930dbbc9dbacb53ad60996e0111e7d8) available in Flipper GH Repo. As a workaround you can comment the below line in the Podfile (present in the ios folder). 

```
:flipper_configuration => flipper_config,
```

Hope this helps!

**Comment by alemar11** [comment]
@mayur-bhandari commenting the line fixed the build problem
