### ISSUE TITLE
Expo: Cannot read property 'BaseInputElement' of undefined

### ISSUE THREAD

**Issue by jayan2019** [cometchat-pro/react-native-chat-app#93]
### Describe the problem
Getting error as `TypeError: Cannot read property 'BaseInputElement' of undefined, js engine: hermes` when i try to implement Cometchat UIKit for React Native V4 with using `expo`

### What was the expected behavior?
App need to run and working

### Reproduction
Create new expo project: `yarn create expo-app AwesomeProject `
Install dependencies: `yarn add @cometchat/chat-uikit-react-native @cometchat/chat-sdk-react-native@4.0.1 @react-native-async-storage/async-storage@1.17.10 @react-native-community/clipboard@1.5.1`
Include init code: `CometChatUIKit.init(uikitSettings)`
Run App: `npx expo run:ios`

Error: `TypeError: Cannot read property 'BaseInputElement' of undefined, js engine: hermes`

![Simulator Screenshot - iPhone 15 Pro Max - 2024-03-21 at 10 41 13](https://github.com/cometchat/cometchat-sample-app-react-native/assets/46986762/4b4cb3fe-d212-48b6-ae18-68b09af34f2c)

### Environment
 "@cometchat/chat-sdk-react-native": "^4.0.6",
 "@cometchat/chat-uikit-react-native": "^4.2.2",
 "@react-native-async-storage/async-storage": "^1.23.1",
 "@react-native-community/clipboard": "^1.5.1",
 "@react-native-community/datetimepicker": "^7.6.3",
 "expo": "~50.0.14",
 "react": "18.2.0",
 "react-native": "0.73.6"

**Comment by jayan2019** [comment]
Full error log:

iOS Bundled 4543ms (node_modules/expo/AppEntry.js)
 ERROR  TypeError: Cannot read property 'BaseInputElement' of undefined, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

![Screenshot 2024-03-21 at 11 07 08](https://github.com/cometchat/cometchat-sample-app-react-native/assets/46986762/2ee49254-794a-4b7c-969e-0d5e50a016d6)

**Comment by jayan2019** [comment]
Hi Prathmesh,

Thank you for your confirmation!

Just as an update, I tried with `"@cometchat/chat-uikit-react-native": "^4.3.3"` and I can see the same issue with this new version also.

Thanks in advance!

**Comment by jayan2019** [comment]
> Prathmesh Parteki (CometChat Team) replied:
> 
> Hi,
> 
> Thank you for reporting the issue. Your issue has been forwarded to our product engineering team who are currently investigating it thoroughly. We truly appreciate your patience during this process.
> 
> Please rest assured, we are committed to providing a resolution as soon as possible. As soon as we have any further updates or information, we will get back to you.
> 
> Regards,
> 
> Prathmesh Parteki CometChat

I really appreciate, Thank you so much!

**Comment by abanobmikaeel** [comment]
Also affected by this issue, and  experiencing it on the latest version. 

Please let us know how to proceed!

**Comment by abanobmikaeel** [comment]
Do you have recommendations for implementing this functionality in an Expo App without this UI Kit? Should we use CometChat Pro React Native SDK? That’s the only that seems to be working for us currently.

**Comment by coyksdev** [comment]
I am also experiencing this issue. There has already been the same issue posted in the UIKit repo since March: https://github.com/cometchat/cometchat-uikit-react-native/issues/63

**Comment by jayan2019** [comment]
I can confirm that UI kit is working fine now. Thanks a lot for the whole team's effort. We appreciate! :tada:
